apiVersion: networking.k8s.io/v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      comment: Kubernetes NetworkPolicy for overlap case.
    name: accept-web-services
  spec:
    ingress:
    - from:
      - ipBlock:
          cidr: 1.2.3.0/24
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      comment: Kubernetes NetworkPolicy for overlap case.
    name: accept-ssh
  spec:
    ingress:
    - from:
      - ipBlock:
          cidr: 1.2.0.0/16
      ports:
      - port: 22
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    annotations:
      comment: Kubernetes NetworkPolicy for overlap case.
    name: accept-mysql
  spec:
    ingress:
    - from:
      - ipBlock:
          cidr: 1.0.0.0/8
      - ipBlock:
          cidr: 8.8.8.8/32
      ports:
      - port: 3306
        protocol: TCP
    podSelector: {}
    policyTypes:
    - Ingress
kind: NetworkPolicyList
